// Code generated by protoc-gen-go. DO NOT EDIT.
// source: updates.proto

package updates

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Player_Wall int32

const (
	Player_FRONT Player_Wall = 0
	Player_BACK  Player_Wall = 1
)

var Player_Wall_name = map[int32]string{
	0: "FRONT",
	1: "BACK",
}

var Player_Wall_value = map[string]int32{
	"FRONT": 0,
	"BACK":  1,
}

func (x Player_Wall) String() string {
	return proto.EnumName(Player_Wall_name, int32(x))
}

func (Player_Wall) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{1, 0}
}

type GameState struct {
	Ball                 *Ball     `protobuf:"bytes,1,opt,name=ball,proto3" json:"ball,omitempty"`
	Players              []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{0}
}

func (m *GameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameState.Unmarshal(m, b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
}
func (m *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(m, src)
}
func (m *GameState) XXX_Size() int {
	return xxx_messageInfo_GameState.Size(m)
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetBall() *Ball {
	if m != nil {
		return m.Ball
	}
	return nil
}

func (m *GameState) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Player struct {
	Xpos                 float32     `protobuf:"fixed32,1,opt,name=Xpos,proto3" json:"Xpos,omitempty"`
	Ypos                 float32     `protobuf:"fixed32,2,opt,name=Ypos,proto3" json:"Ypos,omitempty"`
	Wall                 Player_Wall `protobuf:"varint,3,opt,name=wall,proto3,enum=Player_Wall" json:"wall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{1}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetXpos() float32 {
	if m != nil {
		return m.Xpos
	}
	return 0
}

func (m *Player) GetYpos() float32 {
	if m != nil {
		return m.Ypos
	}
	return 0
}

func (m *Player) GetWall() Player_Wall {
	if m != nil {
		return m.Wall
	}
	return Player_FRONT
}

type Ball struct {
	Xpos                 float32  `protobuf:"fixed32,1,opt,name=Xpos,proto3" json:"Xpos,omitempty"`
	Ypos                 float32  `protobuf:"fixed32,2,opt,name=Ypos,proto3" json:"Ypos,omitempty"`
	Zpos                 float32  `protobuf:"fixed32,3,opt,name=Zpos,proto3" json:"Zpos,omitempty"`
	Xvel                 float32  `protobuf:"fixed32,4,opt,name=Xvel,proto3" json:"Xvel,omitempty"`
	Yvel                 float32  `protobuf:"fixed32,5,opt,name=Yvel,proto3" json:"Yvel,omitempty"`
	Zvel                 float32  `protobuf:"fixed32,6,opt,name=Zvel,proto3" json:"Zvel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ball) Reset()         { *m = Ball{} }
func (m *Ball) String() string { return proto.CompactTextString(m) }
func (*Ball) ProtoMessage()    {}
func (*Ball) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{2}
}

func (m *Ball) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ball.Unmarshal(m, b)
}
func (m *Ball) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ball.Marshal(b, m, deterministic)
}
func (m *Ball) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ball.Merge(m, src)
}
func (m *Ball) XXX_Size() int {
	return xxx_messageInfo_Ball.Size(m)
}
func (m *Ball) XXX_DiscardUnknown() {
	xxx_messageInfo_Ball.DiscardUnknown(m)
}

var xxx_messageInfo_Ball proto.InternalMessageInfo

func (m *Ball) GetXpos() float32 {
	if m != nil {
		return m.Xpos
	}
	return 0
}

func (m *Ball) GetYpos() float32 {
	if m != nil {
		return m.Ypos
	}
	return 0
}

func (m *Ball) GetZpos() float32 {
	if m != nil {
		return m.Zpos
	}
	return 0
}

func (m *Ball) GetXvel() float32 {
	if m != nil {
		return m.Xvel
	}
	return 0
}

func (m *Ball) GetYvel() float32 {
	if m != nil {
		return m.Yvel
	}
	return 0
}

func (m *Ball) GetZvel() float32 {
	if m != nil {
		return m.Zvel
	}
	return 0
}

func init() {
	proto.RegisterEnum("Player_Wall", Player_Wall_name, Player_Wall_value)
	proto.RegisterType((*GameState)(nil), "GameState")
	proto.RegisterType((*Player)(nil), "Player")
	proto.RegisterType((*Ball)(nil), "Ball")
}

func init() { proto.RegisterFile("updates.proto", fileDescriptor_675fc0bf03cd96fd) }

var fileDescriptor_675fc0bf03cd96fd = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0xd0, 0x3f, 0x4f, 0x86, 0x30,
	0x10, 0x06, 0x70, 0x81, 0x02, 0x72, 0xfe, 0x09, 0xe9, 0x84, 0x71, 0xc1, 0x4e, 0x4e, 0x1d, 0xf0,
	0x13, 0x88, 0x89, 0xc6, 0x98, 0xa8, 0xa9, 0x26, 0x22, 0x5b, 0x89, 0xdd, 0x6a, 0xda, 0x00, 0x6a,
	0x5c, 0xfc, 0xec, 0xde, 0x95, 0xbe, 0xfb, 0xbb, 0x3d, 0xf7, 0xbb, 0x3c, 0xbd, 0xa4, 0x70, 0xf2,
	0xe5, 0x3f, 0xf4, 0x6a, 0x16, 0xe9, 0x67, 0xb7, 0x3a, 0x71, 0x0f, 0xd5, 0x9d, 0xfe, 0x34, 0x2f,
	0x2b, 0x1a, 0x3f, 0x03, 0x36, 0x69, 0x6b, 0x9b, 0xa4, 0x4d, 0x2e, 0x8f, 0xba, 0x5c, 0xf6, 0x38,
	0xa8, 0x40, 0xfc, 0x02, 0x4a, 0x6f, 0xf5, 0xaf, 0x99, 0x97, 0x26, 0x6d, 0x33, 0xdc, 0x96, 0xf2,
	0x39, 0xcc, 0x6a, 0xe7, 0xc2, 0x41, 0xb1, 0x11, 0xe7, 0xc0, 0x06, 0xef, 0x96, 0xf0, 0x4e, 0xaa,
	0x42, 0x26, 0x7b, 0x27, 0x4b, 0x37, 0xa3, 0xcc, 0x5b, 0x60, 0x3f, 0x74, 0x2f, 0x43, 0x3b, 0xed,
	0x8e, 0xe3, 0x8b, 0xf2, 0x2d, 0x9c, 0xa5, 0x8d, 0x38, 0x07, 0x46, 0x13, 0xaf, 0x20, 0xbf, 0x55,
	0x4f, 0x8f, 0xaf, 0xf5, 0x01, 0x3f, 0x04, 0xd6, 0x5f, 0xdf, 0x3c, 0xd4, 0x89, 0xf8, 0xc3, 0x44,
	0xcb, 0x7d, 0xcf, 0xa1, 0x8d, 0x64, 0xd9, 0x66, 0x63, 0xb4, 0xe1, 0xdb, 0xd8, 0x86, 0xc5, 0x2e,
	0xe6, 0xd0, 0x25, 0xcb, 0x63, 0x37, 0xda, 0x48, 0x56, 0xc4, 0x2e, 0xe6, 0xa9, 0x08, 0x5f, 0x78,
	0xf5, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xe5, 0x0a, 0xb3, 0x53, 0x01, 0x00, 0x00,
}
