// Code generated by protoc-gen-go. DO NOT EDIT.
// source: updates.proto

package updates

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Wall int32

const (
	Wall_FRONT Wall = 0
	Wall_BACK  Wall = 1
)

var Wall_name = map[int32]string{
	0: "FRONT",
	1: "BACK",
}

var Wall_value = map[string]int32{
	"FRONT": 0,
	"BACK":  1,
}

func (x Wall) String() string {
	return proto.EnumName(Wall_name, int32(x))
}

func (Wall) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{0}
}

type AnyMessage struct {
	// Types that are valid to be assigned to Data:
	//	*AnyMessage_State
	//	*AnyMessage_Start
	//	*AnyMessage_Join
	Data                 isAnyMessage_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AnyMessage) Reset()         { *m = AnyMessage{} }
func (m *AnyMessage) String() string { return proto.CompactTextString(m) }
func (*AnyMessage) ProtoMessage()    {}
func (*AnyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{0}
}

func (m *AnyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnyMessage.Unmarshal(m, b)
}
func (m *AnyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnyMessage.Marshal(b, m, deterministic)
}
func (m *AnyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyMessage.Merge(m, src)
}
func (m *AnyMessage) XXX_Size() int {
	return xxx_messageInfo_AnyMessage.Size(m)
}
func (m *AnyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AnyMessage proto.InternalMessageInfo

type isAnyMessage_Data interface {
	isAnyMessage_Data()
}

type AnyMessage_State struct {
	State *GameState `protobuf:"bytes,1,opt,name=state,proto3,oneof"`
}

type AnyMessage_Start struct {
	Start *GameStart `protobuf:"bytes,2,opt,name=start,proto3,oneof"`
}

type AnyMessage_Join struct {
	Join *PlayerJoin `protobuf:"bytes,3,opt,name=join,proto3,oneof"`
}

func (*AnyMessage_State) isAnyMessage_Data() {}

func (*AnyMessage_Start) isAnyMessage_Data() {}

func (*AnyMessage_Join) isAnyMessage_Data() {}

func (m *AnyMessage) GetData() isAnyMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AnyMessage) GetState() *GameState {
	if x, ok := m.GetData().(*AnyMessage_State); ok {
		return x.State
	}
	return nil
}

func (m *AnyMessage) GetStart() *GameStart {
	if x, ok := m.GetData().(*AnyMessage_Start); ok {
		return x.Start
	}
	return nil
}

func (m *AnyMessage) GetJoin() *PlayerJoin {
	if x, ok := m.GetData().(*AnyMessage_Join); ok {
		return x.Join
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AnyMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AnyMessage_State)(nil),
		(*AnyMessage_Start)(nil),
		(*AnyMessage_Join)(nil),
	}
}

type GameState struct {
	Ball                 *Ball              `protobuf:"bytes,1,opt,name=ball,proto3" json:"ball,omitempty"`
	Players              map[uint32]*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            uint64             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{1}
}

func (m *GameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameState.Unmarshal(m, b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
}
func (m *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(m, src)
}
func (m *GameState) XXX_Size() int {
	return xxx_messageInfo_GameState.Size(m)
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetBall() *Ball {
	if m != nil {
		return m.Ball
	}
	return nil
}

func (m *GameState) GetPlayers() map[uint32]*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameState) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Player struct {
	Xpos                 float32  `protobuf:"fixed32,1,opt,name=Xpos,proto3" json:"Xpos,omitempty"`
	Ypos                 float32  `protobuf:"fixed32,2,opt,name=Ypos,proto3" json:"Ypos,omitempty"`
	Xlast                float32  `protobuf:"fixed32,3,opt,name=Xlast,proto3" json:"Xlast,omitempty"`
	Ylast                float32  `protobuf:"fixed32,4,opt,name=Ylast,proto3" json:"Ylast,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetXpos() float32 {
	if m != nil {
		return m.Xpos
	}
	return 0
}

func (m *Player) GetYpos() float32 {
	if m != nil {
		return m.Ypos
	}
	return 0
}

func (m *Player) GetXlast() float32 {
	if m != nil {
		return m.Xlast
	}
	return 0
}

func (m *Player) GetYlast() float32 {
	if m != nil {
		return m.Ylast
	}
	return 0
}

type Ball struct {
	Xpos                 float32  `protobuf:"fixed32,1,opt,name=Xpos,proto3" json:"Xpos,omitempty"`
	Ypos                 float32  `protobuf:"fixed32,2,opt,name=Ypos,proto3" json:"Ypos,omitempty"`
	Zpos                 float32  `protobuf:"fixed32,3,opt,name=Zpos,proto3" json:"Zpos,omitempty"`
	Xvel                 float32  `protobuf:"fixed32,4,opt,name=Xvel,proto3" json:"Xvel,omitempty"`
	Yvel                 float32  `protobuf:"fixed32,5,opt,name=Yvel,proto3" json:"Yvel,omitempty"`
	Zvel                 float32  `protobuf:"fixed32,6,opt,name=Zvel,proto3" json:"Zvel,omitempty"`
	Xang                 float32  `protobuf:"fixed32,7,opt,name=Xang,proto3" json:"Xang,omitempty"`
	Yang                 float32  `protobuf:"fixed32,8,opt,name=Yang,proto3" json:"Yang,omitempty"`
	Zang                 float32  `protobuf:"fixed32,9,opt,name=Zang,proto3" json:"Zang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ball) Reset()         { *m = Ball{} }
func (m *Ball) String() string { return proto.CompactTextString(m) }
func (*Ball) ProtoMessage()    {}
func (*Ball) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{3}
}

func (m *Ball) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ball.Unmarshal(m, b)
}
func (m *Ball) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ball.Marshal(b, m, deterministic)
}
func (m *Ball) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ball.Merge(m, src)
}
func (m *Ball) XXX_Size() int {
	return xxx_messageInfo_Ball.Size(m)
}
func (m *Ball) XXX_DiscardUnknown() {
	xxx_messageInfo_Ball.DiscardUnknown(m)
}

var xxx_messageInfo_Ball proto.InternalMessageInfo

func (m *Ball) GetXpos() float32 {
	if m != nil {
		return m.Xpos
	}
	return 0
}

func (m *Ball) GetYpos() float32 {
	if m != nil {
		return m.Ypos
	}
	return 0
}

func (m *Ball) GetZpos() float32 {
	if m != nil {
		return m.Zpos
	}
	return 0
}

func (m *Ball) GetXvel() float32 {
	if m != nil {
		return m.Xvel
	}
	return 0
}

func (m *Ball) GetYvel() float32 {
	if m != nil {
		return m.Yvel
	}
	return 0
}

func (m *Ball) GetZvel() float32 {
	if m != nil {
		return m.Zvel
	}
	return 0
}

func (m *Ball) GetXang() float32 {
	if m != nil {
		return m.Xang
	}
	return 0
}

func (m *Ball) GetYang() float32 {
	if m != nil {
		return m.Yang
	}
	return 0
}

func (m *Ball) GetZang() float32 {
	if m != nil {
		return m.Zang
	}
	return 0
}

type GameStart struct {
	YourID               uint32   `protobuf:"varint,1,opt,name=YourID,proto3" json:"YourID,omitempty"`
	Wall                 Wall     `protobuf:"varint,2,opt,name=wall,proto3,enum=Wall" json:"wall,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameStart) Reset()         { *m = GameStart{} }
func (m *GameStart) String() string { return proto.CompactTextString(m) }
func (*GameStart) ProtoMessage()    {}
func (*GameStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{4}
}

func (m *GameStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStart.Unmarshal(m, b)
}
func (m *GameStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStart.Marshal(b, m, deterministic)
}
func (m *GameStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStart.Merge(m, src)
}
func (m *GameStart) XXX_Size() int {
	return xxx_messageInfo_GameStart.Size(m)
}
func (m *GameStart) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStart.DiscardUnknown(m)
}

var xxx_messageInfo_GameStart proto.InternalMessageInfo

func (m *GameStart) GetYourID() uint32 {
	if m != nil {
		return m.YourID
	}
	return 0
}

func (m *GameStart) GetWall() Wall {
	if m != nil {
		return m.Wall
	}
	return Wall_FRONT
}

type PlayerJoin struct {
	PlayerWalls          map[uint32]Wall `protobuf:"bytes,1,rep,name=playerWalls,proto3" json:"playerWalls,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=Wall"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PlayerJoin) Reset()         { *m = PlayerJoin{} }
func (m *PlayerJoin) String() string { return proto.CompactTextString(m) }
func (*PlayerJoin) ProtoMessage()    {}
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{5}
}

func (m *PlayerJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerJoin.Unmarshal(m, b)
}
func (m *PlayerJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerJoin.Marshal(b, m, deterministic)
}
func (m *PlayerJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerJoin.Merge(m, src)
}
func (m *PlayerJoin) XXX_Size() int {
	return xxx_messageInfo_PlayerJoin.Size(m)
}
func (m *PlayerJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerJoin.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerJoin proto.InternalMessageInfo

func (m *PlayerJoin) GetPlayerWalls() map[uint32]Wall {
	if m != nil {
		return m.PlayerWalls
	}
	return nil
}

type Ping struct {
	Timestamp            uint64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{6}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ClientMessage struct {
	// Types that are valid to be assigned to Data:
	//	*ClientMessage_Player
	//	*ClientMessage_Ping
	Data                 isClientMessage_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClientMessage) Reset()         { *m = ClientMessage{} }
func (m *ClientMessage) String() string { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()    {}
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_675fc0bf03cd96fd, []int{7}
}

func (m *ClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessage.Unmarshal(m, b)
}
func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessage.Marshal(b, m, deterministic)
}
func (m *ClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessage.Merge(m, src)
}
func (m *ClientMessage) XXX_Size() int {
	return xxx_messageInfo_ClientMessage.Size(m)
}
func (m *ClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

type isClientMessage_Data interface {
	isClientMessage_Data()
}

type ClientMessage_Player struct {
	Player *Player `protobuf:"bytes,1,opt,name=player,proto3,oneof"`
}

type ClientMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

func (*ClientMessage_Player) isClientMessage_Data() {}

func (*ClientMessage_Ping) isClientMessage_Data() {}

func (m *ClientMessage) GetData() isClientMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ClientMessage) GetPlayer() *Player {
	if x, ok := m.GetData().(*ClientMessage_Player); ok {
		return x.Player
	}
	return nil
}

func (m *ClientMessage) GetPing() *Ping {
	if x, ok := m.GetData().(*ClientMessage_Ping); ok {
		return x.Ping
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientMessage_Player)(nil),
		(*ClientMessage_Ping)(nil),
	}
}

func init() {
	proto.RegisterEnum("Wall", Wall_name, Wall_value)
	proto.RegisterType((*AnyMessage)(nil), "AnyMessage")
	proto.RegisterType((*GameState)(nil), "GameState")
	proto.RegisterMapType((map[uint32]*Player)(nil), "GameState.PlayersEntry")
	proto.RegisterType((*Player)(nil), "Player")
	proto.RegisterType((*Ball)(nil), "Ball")
	proto.RegisterType((*GameStart)(nil), "GameStart")
	proto.RegisterType((*PlayerJoin)(nil), "PlayerJoin")
	proto.RegisterMapType((map[uint32]Wall)(nil), "PlayerJoin.PlayerWallsEntry")
	proto.RegisterType((*Ping)(nil), "Ping")
	proto.RegisterType((*ClientMessage)(nil), "ClientMessage")
}

func init() { proto.RegisterFile("updates.proto", fileDescriptor_675fc0bf03cd96fd) }

var fileDescriptor_675fc0bf03cd96fd = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x9b, 0xd4, 0x49, 0xd7, 0x57, 0x8a, 0x2a, 0x0b, 0x41, 0x58, 0x87, 0xb4, 0x45, 0x1c,
	0x26, 0x0e, 0x91, 0x28, 0x17, 0xc4, 0x61, 0xd2, 0x5a, 0x06, 0x05, 0x04, 0x4c, 0x06, 0x69, 0x6d,
	0xc5, 0xc5, 0xd3, 0xac, 0x28, 0x90, 0x3a, 0x51, 0xe2, 0x0e, 0xf5, 0xc4, 0x87, 0xe0, 0xdb, 0x20,
	0x3e, 0x1c, 0x7a, 0xf6, 0x6b, 0x9b, 0x4d, 0x1c, 0x76, 0x7b, 0xfe, 0xf9, 0xfd, 0xfd, 0x9e, 0xfd,
	0xfe, 0x86, 0xfe, 0xaa, 0xbc, 0x92, 0x46, 0xd5, 0x49, 0x59, 0x15, 0xa6, 0x88, 0x7f, 0x01, 0x9c,
	0xea, 0xf5, 0x47, 0x55, 0xd7, 0x32, 0x55, 0x3c, 0x86, 0xa0, 0x36, 0xd2, 0xa8, 0xc8, 0x3b, 0xf4,
	0x8e, 0x7b, 0x23, 0x48, 0xde, 0xca, 0xa5, 0xfa, 0x82, 0x64, 0xda, 0x12, 0x6e, 0x8b, 0x72, 0x2a,
	0x13, 0xf9, 0x37, 0x73, 0x2a, 0x43, 0x39, 0x95, 0xe1, 0x47, 0xc0, 0xbe, 0x17, 0x99, 0x8e, 0xda,
	0x36, 0xa5, 0x97, 0x9c, 0xe7, 0x72, 0xad, 0xaa, 0xf7, 0x45, 0xa6, 0xa7, 0x2d, 0x61, 0xb7, 0xc6,
	0x21, 0xb0, 0x2b, 0x69, 0x64, 0xfc, 0xd7, 0x83, 0xee, 0xb6, 0x0a, 0x7f, 0x0c, 0xec, 0x52, 0xe6,
	0x39, 0xd5, 0x0f, 0x92, 0xb1, 0xcc, 0x73, 0x61, 0x11, 0x7f, 0x0e, 0x9d, 0xd2, 0x1e, 0x53, 0x47,
	0xfe, 0x61, 0xfb, 0xb8, 0x37, 0x7a, 0xb4, 0xeb, 0x8e, 0x0a, 0xd4, 0x67, 0xda, 0x54, 0x6b, 0xb1,
	0xc9, 0xe3, 0x07, 0xd0, 0x35, 0xd9, 0x52, 0xd5, 0x46, 0x2e, 0x4b, 0xdb, 0x0b, 0x13, 0x3b, 0xb0,
	0x3f, 0x81, 0x7b, 0x4d, 0x19, 0x1f, 0x40, 0xfb, 0x87, 0x5a, 0xdb, 0xd2, 0x7d, 0x81, 0x21, 0x7f,
	0x02, 0xc1, 0xb5, 0xcc, 0x57, 0x8a, 0xae, 0xda, 0xa1, 0x32, 0xc2, 0xd1, 0x57, 0xfe, 0x4b, 0x2f,
	0xfe, 0x06, 0xa1, 0x83, 0x9c, 0x03, 0x9b, 0x95, 0x45, 0x6d, 0xf5, 0xbe, 0xb0, 0x31, 0xb2, 0x39,
	0x32, 0xdf, 0x31, 0x8c, 0xf9, 0x03, 0x08, 0x66, 0xb9, 0xac, 0x8d, 0x6d, 0xc8, 0x17, 0x6e, 0x81,
	0x74, 0x6e, 0x29, 0x73, 0xd4, 0x2e, 0xe2, 0x3f, 0x1e, 0x30, 0x7c, 0x82, 0x3b, 0x1f, 0xce, 0x81,
	0x2d, 0x90, 0xb9, 0xb3, 0x6d, 0x6c, 0xb5, 0xd7, 0x2a, 0xa7, 0x93, 0x6d, 0x6c, 0xb5, 0xc8, 0x02,
	0xd2, 0x12, 0x5b, 0x20, 0x0b, 0x49, 0x4b, 0x6c, 0x26, 0x75, 0x1a, 0x75, 0x48, 0x2b, 0x75, 0x6a,
	0xb5, 0xc8, 0xf6, 0x48, 0x4b, 0x6c, 0x81, 0xac, 0x4b, 0x5a, 0xa9, 0xd3, 0xf8, 0x64, 0x3b, 0xd8,
	0xca, 0xf0, 0x87, 0x10, 0xce, 0x8b, 0x55, 0xf5, 0xee, 0x35, 0xbd, 0x2f, 0xad, 0x70, 0xe0, 0x3f,
	0x71, 0xe0, 0x78, 0x89, 0xfb, 0xa3, 0x20, 0xb9, 0xb0, 0x03, 0x47, 0x14, 0xff, 0xf6, 0x00, 0x76,
	0xc6, 0xe1, 0x27, 0xd0, 0x73, 0x73, 0xc5, 0x14, 0x7c, 0x09, 0xf4, 0xc0, 0x41, 0xc3, 0x5a, 0x14,
	0xda, 0x6d, 0x67, 0x84, 0xa6, 0x60, 0xff, 0x0c, 0x06, 0xb7, 0x13, 0xfe, 0x33, 0xf2, 0x61, 0x73,
	0xe4, 0xdb, 0x86, 0x1a, 0x03, 0x7f, 0x0a, 0xec, 0x3c, 0xd3, 0xe9, 0x4d, 0x6f, 0x79, 0xb7, 0xbc,
	0x15, 0x5f, 0x40, 0x7f, 0x92, 0x67, 0x4a, 0x9b, 0xcd, 0xcf, 0x3a, 0x82, 0xd0, 0x35, 0x43, 0xd6,
	0xde, 0x78, 0x69, 0xda, 0x12, 0xb4, 0xc1, 0x87, 0xc0, 0xca, 0x4c, 0xa7, 0x64, 0xb6, 0x20, 0xc1,
	0x32, 0xf8, 0x5d, 0x10, 0x6e, 0xbe, 0xcb, 0xb3, 0x21, 0x30, 0xec, 0x88, 0x77, 0x21, 0x78, 0x23,
	0x3e, 0x7f, 0xfa, 0x3a, 0x68, 0xf1, 0x3d, 0x60, 0xe3, 0xd3, 0xc9, 0x87, 0x81, 0x77, 0x19, 0xda,
	0x3f, 0xfd, 0xe2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x9e, 0xff, 0x0f, 0xe4, 0x03, 0x00,
	0x00,
}
